misconfigurations:
  - id: AVD-KSV-0120 # No Sysmodule Capability
    paths:
      - "kubernetes/wireguard.yaml"
    statement: Needed
  - id: AVD-KSV-0104 # No Seccomp Unconfined
    paths:
      - "kubernetes/wireguard.yaml"
      - "kubernetes/speedtest.yaml"
    statement: Needed
  - id: AVD-KSV-0030 # Use Default Seccomp
    paths:
      - "kubernetes/wireguard.yaml"
      - "kubernetes/speedtest.yaml"
    statement: Needed
  - id: AVD-KSV-0106 # Drop Caps Add Bind Svc
    paths:
      - "kubernetes/wireguard.yaml"
      - "kubernetes/speedtest.yaml"
    statement: Needed
  - id: AVD-KSV-0022 # No Non Default Capabilities
    paths:
      - "kubernetes/wireguard.yaml"
    statement: Needed
  - id: AVD-KSV-0003 # Drop Default Capabilities
    paths:
      - "kubernetes/wireguard.yaml"
    statement: Needed
  - id: AVD-KSV-0021 # Use High Gid
    paths:
      - "kubernetes/wireguard.yaml"
    statement: Needed
  - id: AVD-KSV-0020 # Use High Uid
    paths:
      - "kubernetes/wireguard.yaml"
    statement: Needed
  - id: AVD-KSV-0014 # Use Readonly Filesystem
    paths:
      - "kubernetes/wireguard.yaml"
    statement: Needed
  - id: AVD-KSV-0012 # No Root
    paths:
      - "kubernetes/wireguard.yaml"
    statement: Needed
  - id: AVD-KSV-0001 # No Self Privesc
    paths:
      - "kubernetes/wireguard.yaml"
    statement: Needed
