misconfigurations:
  - id: AVD-GIT-0001 # GitHub repository should be set to be private.
    statement: No es una vulnerabilidad
  - id: AVD-KSV-0120 # No Sysmodule Capability
    paths:
      - "kubernetes/apps/manifests/wireguard.yaml"
    statement: Needed
  - id: AVD-KSV-0104 # No Seccomp Unconfined
    paths:
      - "kubernetes/apps/manifests/wireguard.yaml"
      - "kubernetes/apps/manifests/speedtest.yaml"
    statement: Needed
  - id: AVD-KSV-0030 # Use Default Seccomp
    paths:
      - "kubernetes/apps/manifests/wireguard.yaml"
      - "kubernetes/apps/manifests/speedtest.yaml"
    statement: Needed
  - id: AVD-KSV-0106 # Drop Caps Add Bind Svc
    paths:
      - "kubernetes/apps/manifests/wireguard.yaml"
      - "kubernetes/apps/manifests/speedtest.yaml"
      - "kubernetes/apps/manifests/home-assistant.yaml"
    statement: Needed
  - id: AVD-KSV-0022 # No Non Default Capabilities
    paths:
      - "kubernetes/apps/manifests/wireguard.yaml"
      - "kubernetes/apps/manifests/speedtest.yaml"
      - "kubernetes/pihole/pihole.yaml"
      - "kubernetes/apps/manifests/home-assistant.yaml"
    statement: Needed
  - id: AVD-KSV-0003 # Drop Default Capabilities
    paths:
      - "kubernetes/apps/manifests/wireguard.yaml"
    statement: Needed
  - id: AVD-KSV-0021 # Use High Gid
    paths:
      - "kubernetes/apps/manifests/wireguard.yaml"
    statement: Needed
  - id: AVD-KSV-0020 # Use High Uid
    paths:
      - "kubernetes/apps/manifests/wireguard.yaml"
    statement: Needed
  - id: AVD-KSV-0014 # Use Readonly Filesystem
    paths:
      - "kubernetes/apps/manifests/wireguard.yaml"
      - "kubernetes/apps/manifests/speedtest.yaml"
      - "kubernetes/pihole/pihole.yaml"
      - "kubernetes/apps/manifests/home-assistant.yaml"
    statement: Needed
  - id: AVD-KSV-0012 # No Root
    paths:
      - "kubernetes/apps/manifests/wireguard.yaml"
      - "kubernetes/apps/manifests/speedtest.yaml"
      - "kubernetes/pihole/pihole.yaml"
      - "kubernetes/apps/manifests/home-assistant.yaml"
      - "kubernetes/cloudflared.yaml"
    statement: Needed
  - id: AVD-KSV-0001 # No Self Privesc
    paths:
      - "kubernetes/apps/manifests/wireguard.yaml"
      - "kubernetes/pihole/pihole.yaml"
      - "kubernetes/apps/manifests/home-assistant.yaml"
      - "kubernetes/cloudflared.yaml"
    statement: Needed
  - id: AVD-KSV-0021
    statement: Temporalmente desactivado
  - id: AVD-KSV-0020
    statement: Temporalmente desactivado
  - id: AVD-KSV-0117 # No Privilege Port Binding
    paths:
      - "kubernetes/pihole/pihole.yaml"
    statement: Needed
  - id: AVD-KSV-0017 # No Privileged Containers
    paths:
      - "kubernetes/pihole/pihole.yaml"
      - "kubernetes/apps/manifests/home-assistant.yaml"
    statement: Needed
  - id: AVD-KSV-0009 # No Host Network
    paths:
      - "kubernetes/pihole/pihole.yaml"
      - "kubernetes/apps/manifests/home-assistant.yaml"
    statement: Needed
  - id: AVD-KSV-0023
    path:
      - "kubernetes/apps/manifests/home-assistant.yaml"
    statement: Needed
