apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: common-minimal-cluster
spec:
  teamId: "common"
  volume:
    size: 20Gi
  numberOfInstances: 1
  users:
    aictur:  # database owner
    - superuser
    - createdb
    coder_user: []  # role for application foo
  databases:
    coder: aictur  # dbname: owner
  postgresql:
    version: "16"