apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: true
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 8.8.8.8
      volumes:
      - name: etc
        persistentVolumeClaim:
          claimName: pihole-data
      - name: dominios-internos
        configMap:
          name: dominios-internos
      - name: dnsmasq
        persistentVolumeClaim:
          claimName: pihole-dnsmasq-data
      containers:
        - name: pihole
          image: pihole/pihole:2024.07.0
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: pihole-secrets
          env:
            - name: TZ
              value: "Europe/Madrid"
            - name: WEB_PORT
              value: "8800"
            - name: INTERFACE
              value: enp6s0
            - name: DNSMASQ_LISTENING
              value: all
          securityContext:
            privileged: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            # - containerPort: 67 # Solo es necesario si usamos DHCP
            #   protocol: UDP
            - containerPort: 8800
              protocol: TCP
          volumeMounts:
            - name: etc
              mountPath: /etc/pihole
            - name: dominios-internos
              mountPath: /etc/pihole/custom.list
              subPath: custom.list
            - name: dnsmasq
              mountPath: /etc/dnsmasq.d
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 2Gi
              cpu: 1