# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-staging
#   namespace: cert-manager
# spec:
#   acme:
#     email: aaictur@gmail.com
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       name: test-secret-cloudflare
#     solvers:
#     - dns01:
#         cloudflare:
#           apiTokenSecretRef:
#             name: cloudflare-api-token-secret
#             key: api-token
# ---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  # namespace: cert-manager
spec:
  acme:
    email: aaictur@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: secret-cloudflare
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token

