name: Despliegue
run-name: Desplegando PROD
on:
  push:
    branches:
      - main
jobs:
  Preparacion:
    uses: ./.github/workflows/analyze.yml
  Despliegue:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Wireguard
        run: sudo apt update -y && sudo apt install -y wireguard
      - name: Configurar Wireguard
        run: echo "${{ secrets.WG_CONFIG }}" | base64 -d 2> /dev/null > wg0.conf && sudo wg setconf wg0 wg0.conf
      - name: Arrancar Wireguard
        run: sudo wq-quick up wg0
      - name: Test WG0
        run: curl 192.168.1.30:8123
      # - uses: NexRX/WireGuard-Session@v1
      #   with:
      #     wg-client-b64: ${{ secrets.WG_CONFIG }}
      #     timeout-address: "10.8.0.1"
      #     timeout-seconds: 180
      - name: Generar dominios de TF
        run: ./generate-domains-tf.sh
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8
      - uses: terraform-cache/terraform-cache@v1
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
