name: Despliegue
run-name: Desplegando PROD
on:
  push:
    branches:
      - main
jobs:
  Preparacion:
    uses: ./.github/workflows/analyze.yml
  Deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      # - uses: NexRX/WireGuard-Session@v1
      #   with:
      #     wg-client-b64: ${{ secrets.WG_CONFIG }}
      #     timeout-address: "192.168.1.30"
      #     timeout-seconds: 180
      - name: Set up WireGuard
        uses: egor-tensin/setup-wireguard@v1
        with:
          endpoint: vpn.aictur.dev:30000
          endpoint_public_key: ${{ secrets.WG_PUBLIC_KEY }}
          ips: 10.8.0.3/24
          allowed_ips: 0.0.0.0/0,::/0
          private_key: ${{ secrets.WG_PRIVATE_KEY }}
          preshared_key: ${{ secrets.WG_SHARED_KEY }}
      - name: Generar dominios de TF
        run: ./generate-domains-tf.sh
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8
      - uses: terraform-cache/terraform-cache@v1
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
