name: Despliegue
run-name: Desplegando PROD
on:
  push:
    branches:
      - main
jobs:
  Preparacion:
    uses: ./.github/workflows/analyze.yml
  Despliegue:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.76.1
      - name: Test Tailscale
        run: curl http://${{ secrets.TS_HOST_IP }}:8123
      - name: Generar dominios de TF
        run: ./generate-domains-tf.sh
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8
      - uses: terraform-cache/terraform-cache@v1
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
